### ISSUE TITLE
Error in plot_krona function

### ISSUE THREAD

**Issue by adimascf** [cpauvert/psadd#3]
Hello @cpauvert 

Thank you for developing this package. I use this to create a krona plot from the mothur share file, which runs smoothly. However, when I use qiime2 files as an input for phyloseq object, I get this error:

```Error in `[.data.frame`(df, , c("Abundance", variable, rank_names(physeq))) : 
  undefined columns selected
Calls: plot_krona -> [ -> [.data.frame```

This is my command: `plot_krona(physeq_do, "GP-krona", "sample_id", trim = F)`

Is something that I miss here?

Thank you

**Comment by cpauvert** [comment]
Hi @adimascf,
Thanks for your message. Without knowing how your `phyloseq` object is organized is hard for me to help you. Could you please indicate the columns of the metadata associated with your samples, using the following command?

```{r}
head( sample_data( physeq_do ) )
```

And maybe  the output of the short command to get the structure of the main dataframe with which the plot_krona works with.
```{r}
str( psmelt( physeq_do ) )
```

Best,

**Comment by adimascf** [comment]
Thank you for your quick reply @cpauvert 

This is the output of `head( sample_data( physeq_do ) )`:
```
Sample Data:        [6 samples by 2 sample variables]:
              sample_id region
SRR12374556 SRR12374556    ITS
SRR12374557 SRR12374557    ITS
SRR12374560 SRR12374560    ITS
SRR12374565 SRR12374565    ITS
SRR12374576 SRR12374576    ITS
SRR12374587 SRR12374587    ITS 
```

This is the output when I run `str( psmelt( physeq_do ) )`:
```
'data.frame':   3648 obs. of  11 variables:
 $ OTU      : chr  "8fd00ed8b0d8c686b86e040711c1de74" "0c2f28439c66fe527b7dabaafdab1520" "8fd00ed8b0d8c686b86e040711c1de74" "8fd00ed8b0d8c686b86e040711c1de74" ...
 $ Sample   : chr  "SRR12374557" "SRR12374565" "SRR12374587" "SRR12374556" ...
 $ Abundance: num  64258 48154 41647 34838 31548 ...
 $ sample_id: chr  "SRR12374557" "SRR12374565" "SRR12374587" "SRR12374556" ...
 $ region   : chr  "ITS" "ITS" "ITS" "ITS" ...
 $ Kingdom  : chr  "Streptophyta" "Streptophyta" "Streptophyta" "Streptophyta" ...
 $ Phylum   : chr  "NA" "NA" "NA" "NA" ...
 $ Class    : chr  "Brassicales" "Apiales" "Brassicales" "Brassicales" ...
 $ Order    : chr  "Brassicaceae" "Apiaceae" "Brassicaceae" "Brassicaceae" ...
 $ Family   : chr  "Lepidium" "Coriandrum" "Lepidium" "Lepidium" ...
 $ Genus    : chr  "Lepidium spinosum" "Coriandrum sativum" "Lepidium spinosum" "Lepidium spinosum" ...
```

**Comment by cpauvert** [comment]
Hum, this is strange, all of the required columns are present in the `psmelt` output: "Abundance", "sample_id" and the different ranks.

Could you try maybe to run the following to check if the access to the rank_names is the culprit?:

```{r}
df <- psmelt( physeq_do )
df_subset <- df[ ,c("Abundance", "sample_id", rank_names(physeq_do)) ]
str(df_subset)
```



This way, we are mimicking the culprit [line of code](https://github.com/cpauvert/psadd/blob/6407bd88c1436101640e103a927515ada8c7f520/R/plot_functions.R#L235) that seems to set out the error 

**EDIT**: I adjusted the command line to your use case

**Comment by adimascf** [comment]
Yes, the output is identical to `plot_krona()` function.:
```
Error in `[.data.frame`(df, , c("Abundance", "sample_id", rank_names(physeq_do))) : 
  undefined columns selected
Calls: [ -> [.data.frame
```

Do you think this is because I only have 6 levels on my taxonomy classification, and no species variable appears on my `df`,  whereas `rank_names(physeq_do)` gives me 7 taxonomic levels?
```
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
```

Thank you again for taking a closer to this

**Comment by cpauvert** [comment]
> Yes, the output is identical to `plot_krona()` function.:
> 
Perfect, thank you!

> Do you think this is because I only have 6 levels on my taxonomy classification, and no species variable appears on my `df`, whereas `rank_names(physeq_do)` gives me 7 taxonomic levels?
> 
> ```
> [1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
> ```
> 
**Yes**, this is it. For instance, if you run the following code, you can reproduce the error:

```
df <- data.frame(
  "sample_id" = 1:3,
  "Genus" = LETTERS[1:3]
)
df[, c("sample_id", "Genus","Species")]
```

But I think you might have another problem. I could [see](https://github.com/cpauvert/psadd/issues/3#issuecomment-1425556857) that your taxonomic data might be shifted. You have *Lepidium spinosum* listed as Genus, when it should be Species. So you might want to import your taxomic table again. If you had the Kingdom (or Domain) Bacteria, this should solve it.


> Thank you again for taking a closer to this

You're welcome, thank you for using this!


**EDIT**: let me know if this worked and I can close the issue ;)

**Comment by adimascf** [comment]
Yes, you are right.
Thank you for your explanation and suggestion, very helpful. I think I will add one column to my taxonomic table and try rerunning again. I will let you know the result.

**Comment by adimascf** [comment]
Hi @cpauvert 

Sorry for the late response.  I have managed to generate the krona chart successfully without error using the `psadd` package.
My workaround was to add one column (in my case subkingdom) to my taxonomy file before training the classifier file.

Thank you again for your help and the package, very helpful!
