### ISSUE TITLE
plot_krona() unable to work without KronaTools

### ISSUE THREAD

**Issue by AngelicaMiraples** [cpauvert/psadd#4]
Hi Charlie, 

I'm looking to use the plot_krona() function in R studio for some microbiome analyses. 

I had installed the dependencies for krona using your code: 
remotes::install_github("cpauvert/psadd")

Upon running plot_krona(), the following error would appear: 
 KronaTools are not installed. Please see https://github.com/marbl/Krona/wiki/KronaTools.

I have learned that KronaTools is a command line package, so I downloaded in Ubuntu using the code:
## Install KronaTools 
curl -LOk https://github.com/marbl/Krona/releases/download/v2.8.1/KronaTools-2.8.1.tar

tar xvf KronaTools-2.8.1.tar

cd KronaTools-2.8.1

sudo ./install.pl

However, I get the same error when running plot_krona() in R studio. 

IS there something I'm missing? Any advice greatly appreciated. 

Best,
Angelica

**Comment by cpauvert** [comment]
Hi @AngelicaMiraples , 
Thank you very much for your interest in this package, I'm sorry it did not work as expected, but I'm glad you provided many information for me to help you!

You had the right approach by following the link and installing the `KronaTools` with all the steps you listed. It is possible that `KronaTools` **is** installed but that `psadd` or `R` (and therefore `Rstudio`) do not know where to find it.

- Was there any error or warning messages during `sudo ./install.pl` ?

- Could you please open a Terminal (command line) window in Ubuntu on the computer where you installed `KronaTools` and run the following command:

```bash
which ktImportText
```
This command should indicate what is the path to one of the program of the KronaTools that I use in `psadd`.

If nothing is displayed, it means that the installation went wrong somewhere, because Ubuntu cannot find the program.
Otherwise, it should print a path to the program.

- Could you please run the following command and indicate the output? The first is the default installation path of the `KronaTools` (see [code](https://github.com/marbl/Krona/blob/d1479b305b1052ce54d43d395a34283319928d48/KronaTools/install.pl#L14)) and the second indicates the path that you computer is looking at to find programs

```bash
ls -al /usr/local/bin/ktImportText
echo ${PATH}
```

Hope that we will get more insight into this and that you can continue your analysis.
Depending on the results and where the problem stems from, you might need to close https://github.com/marbl/Krona/issues/189

Best,
Charlie

**Comment by AngelicaMiraples** [comment]
Hi @cpauvert, 

Thank you so much for your reply! 

Upon installation, there were no error messages to: 
`sudo ./install.pl`

After running `which ktImportText` in Ubuntu, a path was returned :
/home/angelica/miniconda3/bin/ktImportText
 

I also ran `ls -al /usr/local/bin/ktImportText
echo ${PATH}`

(base) angelica@angelica_xps15:~$ ls -al /usr/local/bin/ktImportText
echo ${PATH}
lrwxrwxrwx 1 root root 53 Dec  5 09:48 /usr/local/bin/ktImportText -> /home/angelica/KronaTools-2.8.1/scripts/ImportText.pl
/home/angelica/miniconda3/bin:/home/angelica/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/dotnet:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/Angelica/AppData/Local/Microsoft/WindowsApps:/snap/bin


Looks like they are in different locations? 

And yes, I will close https://github.com/marbl/Krona/issues/189 

Best,
Angelica

**Comment by cpauvert** [comment]
> After running `which ktImportText` in Ubuntu, a path was returned : `/home/angelica/miniconda3/bin/ktImportText`
> 
The presence of 'miniconda' in the path here indicates that the installation took place in a conda environment whether you wanted it or not. Seeing later the `(base) angelica@angelica_xps15` it seems that you ran the installation command for KronaTools in the `base` conda environment. R and Rstudio usually have some trouble accessing conda environments.

But strangely enough, the command below indicates that there is also an installation of the KronaTools in the "normal" environment (meaning "not conda").

Did you installed the KronaTools several times?

```
(base) angelica@angelica_xps15:~$ ls -al /usr/local/bin/ktImportText
lrwxrwxrwx 1 root root 53 Dec 5 09:48 /usr/local/bin/ktImportText -> /home/angelica/KronaTools-2.8.1/scripts/ImportText.pl
```

Maybe we can narrow it down and assess if R and Rstudio have issues finding it, could you please run the following command in R and display the output here? _Tip_: you can use three backticks (like these: ```) before and after your message to make it clearer 

```R
(out <- system(command = "which ktImportText", intern = TRUE))
```

**Comment by AngelicaMiraples** [comment]
Apologies for the confusion -- yes had installed KronaTools twice. The most recent time was using the installation method annotated above, but once another time via conda. 

In R: 
```
> (out <- system(command = "which ktImportText", intern = TRUE))
[1] "/usr/bin/which: no ktImportText in (/x86_64-w64-mingw32.static.posix/bin:/usr/bin:/c/Program Files/R/R-4.3.2/bin/x64:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/dotnet:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Users/Angelica/AppData/Local/Microsoft/WindowsApps:/c/Program Files/RStudio/resources/app/bin/quarto/bin:/c/Program Files/RStudio/resources/app/bin/postback)"
attr(,"status")
[1] 1
Warning message:
In system(command = "which ktImportText", intern = TRUE) :
  running command 'which ktImportText' had status 1
  ```
  
 Best,
 Angelica

**Comment by cpauvert** [comment]
Ok thanks, so a double installation is also likely to confuse programs.

R does know where to find the KronaTools despite two different installations.
It seems that R cannot look programs the same way as in the terminal, meaning the PATH which is the collection of paths that contain programs is different in the terminal and in R.

To ensure this, you could run  `Sys.getenv("PATH")` in R and compare with https://github.com/cpauvert/psadd/issues/4#issuecomment-1845511251

**Comment by cpauvert** [comment]
Thanks for your help as well. The potential solutions I foresee depends if you are using other functions in `psadd` outside of the `plot_krona()`.

If you only use the `plot_krona()` function, I can post a replacement function to fix your issue now and can think long-term to better include different installations of the KronaTools in `psadd`.

If you are using others functions here, a solution would need more time to think of a better fix.

**Comment by cpauvert** [comment]
Okay so not perfect, but a quick fix to let you continue exploring your data!

REinstall the package with this fix

```r
remotes::install_github("cpauvert/psadd@with-krona-path")
```
Run the modified `plot_krona()` as follow:

```r 
plot_krona(GlobalPatterns,"GP-krona", "SampleType", krona_path = "/usr/local/bin/ktImportText")
# OR
plot_krona(GlobalPatterns,"GP-krona", "SampleType", krona_path = "/home/angelica/miniconda3/bin/ktImportText")
```

Let me know if that helps!
Best,

**Comment by AngelicaMiraples** [comment]
Thanks so much Charlie. You've been a huge help. 

I am only using the `plot_krona()` function so I believe this new code will certainly be useful. Will get back to you on this!

Best,
Angelica

**Comment by AngelicaMiraples** [comment]
Hi Charlie, 

Unforunately, no luck with the path inclusion: 

```
> remotes::install_github("cpauvert/psadd@with-krona-path")
Downloading GitHub repo cpauvert/psadd@with-krona-path
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: vctrs (0.6.4 -> 0.6.5) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
vctrs (0.6.4 -> 0.6.5) [CRAN]
Skipping 1 packages not available: phyloseq
Installing 1 packages: vctrs
Installing package into ‘C:/Users/Angelica/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/vctrs_0.6.5.zip'
Content type 'application/zip' length 1334316 bytes (1.3 MB)
downloaded 1.3 MB

package ‘vctrs’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘vctrs’
Warning: restored ‘vctrs’

The downloaded binary packages are in
	C:\Users\Angelica\AppData\Local\Temp\RtmpCkG2Rc\downloaded_packages
── R CMD build ─────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Angelica\AppData\Local\Temp\RtmpCkG2Rc\remotes55482c3f38bd\cpauvert-psadd-7d9f113/DESCRIPTION' ...
─  preparing 'psadd':
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'psadd_0.1.3.tar.gz'
   
Installing package into ‘C:/Users/Angelica/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'psadd' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (psadd)
```

There was also a warning message. Not sure if this would effect the package. 

```
Warning message:
In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Angelica\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\Angelica\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied
```

Running plot_krona() on my phyloseq data indicates KronaTools not installed 

```
> plot_krona(ps_pollenp, "pollen_DNA", "PollenDNATreatment", krona_path = "/usr/local/bin/ktImportText", trim = T)
Error in plot_krona(ps_pollenp, "pollen_DNA", "PollenDNATreatment", krona_path = "/usr/local/bin/ktImportText",  : 
  KronaTools are not installed. Please see https://github.com/marbl/Krona/wiki/KronaTools. And provide a valid path to ktImportText
```

**Comment by cpauvert** [comment]
Thanks for trying @AngelicaMiraples, ok it's a pity.

But I notice in the R outputs (`C:/Users/Angelica/AppData/Local/R/win-library/4.3`) you are posting now that R and Rstudio are ran from Windows??

However, you installed the KronaTools on Ubuntu https://github.com/cpauvert/psadd/issues/4#issue-2026467072, this is why I suggested to use the paths in https://github.com/cpauvert/psadd/issues/4#issuecomment-1845622512 because `/usr/local/bin/ktImportText` or `/home/angelica/miniconda3/bin/ktImportText` are Linux paths not Windows paths...

One option would be to install the KronaTools on Windows (but [this seems unsupported according to the documention](https://github.com/marbl/Krona/wiki/Requirements#supported-operating-systems)).

The alternative is for you to use R and Rstudio on the (Ubuntu) computer where you previously installed the KronaTools

**Comment by AngelicaMiraples** [comment]
Of course it was something this simple. Sorry for all the hassle with this! But thank you so much for your time Charlie. 

Best,
Angelica :)

**Comment by cpauvert** [comment]
> Of course it was something this simple. Sorry for all the hassle with this! But thank you so much for your time Charlie.

So before closing the issue, did you use the regular install of `psadd` or the modified installation like in https://github.com/cpauvert/psadd/issues/4#issuecomment-1845622512 ?


> Best, Angelica :)

Good exploration with the pollen data ; )

**Comment by AngelicaMiraples** [comment]
For this, I used the modified installation!
